# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b290b47699b3af602e1d41fcc86fa7ec4ed7f07af56876c7132765d4dbc4bbe565fc1aec4a14531fb48692e4a8b18496dceb2c42b613d87d66f5cd25ec081136

test:
  secret_key_base: 004cf3ae832d660737f25fedb8ec83c54a9cf504da3a328d62663b81ee5da415c917a56a48f651b64ea181e7549f4486392a7f337ce0bb8f292bfb372024f463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
